def rainbow_curve_simple(point_x, point_y, color_list, bg_color):
    import turtle
    pen = turtle.Turtle()
    turtle.bgcolor(bg_color)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.color(color_list[0])
    pen.pensize(13)
    pen.down()
    pen.left(90)
    pen.circle(70, 180)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.right(90)
    pen.forward(10)
    pen.right(90)
    pen.color(color_list[1])
    pen.down()
    pen.circle(60, 180)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.right(90)
    pen.forward(20)
    pen.right(90)
    pen.color(color_list[2])
    pen.down()
    pen.circle(50, 180)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.right(90)
    pen.forward(30)
    pen.right(90)
    pen.color(color_list[3])
    pen.down()
    pen.circle(40, 180)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.right(90)
    pen.forward(40)
    pen.right(90)
    pen.color(color_list[4])
    pen.down()
    pen.circle(30, 180)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.right(90)
    pen.forward(50)
    pen.right(90)
    pen.color(color_list[5])
    pen.down()
    pen.circle(20, 180)
    pen.up()
    pen.setpos(point_x, point_y)
    pen.right(90)
    pen.forward(60)
    pen.right(90)
    pen.color(color_list[6])
    pen.down()
    pen.circle(10, 180)


list_of_colors = ['red', 'orange', 'yellow', 'green', 'cyan', 'pink', 'purple']
